force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Object used for linked budget headings to budget lines and funding requests.</description>
    <label>Budget</label>
    <nameField>
        <displayFormat>BID-{000000000}</displayFormat>
        <label>Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/Awarded__c.field-meta.xml
<CustomField>
    <fullName>Awarded__c</fullName>
    <inlineHelpText>Sum of all awarded amounts associated with this budget heading</inlineHelpText>
    <label>Awarded</label>
    <summarizedField>Budget_Line__c.Awarded__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <inlineHelpText>Sum of all changes associated with this budget heading</inlineHelpText>
    <label>Change</label>
    <summarizedField>Budget_Line__c.Change__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Funding_Request__c.field-meta.xml
<CustomField>
    <fullName>Funding_Request__c</fullName>
    <label>Funding Request</label>
    <referenceTo>outfunds__Funding_Request__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Heading__c.field-meta.xml
<CustomField>
    <fullName>Heading__c</fullName>
    <inlineHelpText>This is the heading for this budget item</inlineHelpText>
    <label>Heading</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <inlineHelpText>Sum of all payment amounts associated with this budget heading</inlineHelpText>
    <label>Payment Amount</label>
    <summarizedField>Budget_Line__c.Payment_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <inlineHelpText>Sum of all plans associated with this budget heading</inlineHelpText>
    <label>Plan</label>
    <summarizedField>Budget_Line__c.Plan__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Recommended__c.field-meta.xml
<CustomField>
    <fullName>Recommended__c</fullName>
    <inlineHelpText>Sum of all recommended amounts associated with this budget heading</inlineHelpText>
    <label>Recommended</label>
    <summarizedField>Budget_Line__c.Recommended__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Spend__c.field-meta.xml
<CustomField>
    <fullName>Spend__c</fullName>
    <inlineHelpText>Sum of all spend associated with this budget heading</inlineHelpText>
    <label>Spend</label>
    <summarizedField>Budget_Line__c.Spend__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget__c/fields/Variance__c.field-meta.xml
<CustomField>
    <fullName>Variance__c</fullName>
    <inlineHelpText>Sum of all variance associated with this budget heading</inlineHelpText>
    <label>Variance</label>
    <summarizedField>Budget_Line__c.Variance__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/Budget_Line__c.object-meta.xml
<CustomObject>
    <description>Object used for storing the individual budget lines for a funding request</description>
    <label>Budget Line</label>
    <nameField>
        <displayFormat>BLID-{000000000}</displayFormat>
        <label>Budget Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line__c/fields/Awarded__c.field-meta.xml
<CustomField>
    <fullName>Awarded__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is the awarded amount for this budget line</inlineHelpText>
    <label>Awarded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Budget Lines</relationshipLabel>
    <relationshipName>Budget_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <defaultValue>0.00</defaultValue>
    <inlineHelpText>This is an amount provided as a change request against the original awarded amount</inlineHelpText>
    <label>Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>Payment__r.outfunds__Scheduled_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>outfunds__Disbursement__c</referenceTo>
    <relationshipLabel>Budget Lines</relationshipLabel>
    <relationshipName>Budget_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is the amount set for this budget line against the payment</inlineHelpText>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <defaultValue>0.00</defaultValue>
    <inlineHelpText>This is the planned spend amount against this budget heading</inlineHelpText>
    <label>Plan</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Recommended__c.field-meta.xml
<CustomField>
    <fullName>Recommended__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>This is the recommended amount based on the assessment of this budget</inlineHelpText>
    <label>Recommended</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Spend__c.field-meta.xml
<CustomField>
    <fullName>Spend__c</fullName>
    <defaultValue>0.00</defaultValue>
    <inlineHelpText>This is the spend amount submitted during reporting against this budget line</inlineHelpText>
    <label>Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Variance__c.field-meta.xml
<CustomField>
    <fullName>Variance__c</fullName>
    <formula>Payment_Amount__c - Spend__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/outfunds__Disbursement__c/fields/Awarded__c.field-meta.xml
<CustomField>
    <fullName>Awarded__c</fullName>
    <label>Awarded</label>
    <summarizedField>Budget_Line__c.Awarded__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/outfunds__Disbursement__c/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <label>Change</label>
    <summarizedField>Budget_Line__c.Change__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/outfunds__Disbursement__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <summarizedField>Budget_Line__c.Payment_Amount__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/outfunds__Disbursement__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <summarizedField>Budget_Line__c.Plan__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/outfunds__Disbursement__c/fields/Recommended__c.field-meta.xml
<CustomField>
    <fullName>Recommended__c</fullName>
    <label>Recommended</label>
    <summarizedField>Budget_Line__c.Recommended__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/outfunds__Disbursement__c/fields/Spend__c.field-meta.xml
<CustomField>
    <fullName>Spend__c</fullName>
    <label>Spend</label>
    <summarizedField>Budget_Line__c.Spend__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/outfunds__Disbursement__c/fields/Variance__c.field-meta.xml
<CustomField>
    <fullName>Variance__c</fullName>
    <label>Variance</label>
    <summarizedField>Budget_Line__c.Variance__c</summarizedField>
    <summaryForeignKey>Budget_Line__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/BudgetController.cls
/**
 * @description       : controller class with methods used during the budget management process
 * @author            : daniel@hyphen8.com
 * @group             : 
 * @last modified on  : 17/04/2021
 * @last modified by  : daniel@hyphen8.com
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   04-16-2021   daniel@hyphen8.com   Initial Version
**/
public with sharing class BudgetController {
    
    /**
    * @description      method to return budget headings with budget lines
    * @param            string recordId 
    * @return           List<Budget__c> 
    **/
    @AuraEnabled
    public static List<Budget__c> getBudgetLines(string recordId) {
        try {
            return [SELECT Id, Heading__c, Recommended__c, Plan__c, Awarded__c, Spend__c, Variance__c, Change__c, Payment_Amount__c, (SELECT Id, Recommended__c, Plan__c, Awarded__c, Payment_Amount__c, Change__c, Spend__c, Variance__c, Date__c FROM Budget_Lines__r ORDER BY Date__c ASC) FROM Budget__c WHERE Funding_Request__c=:recordId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description      method to return disbursements/payments for use within the budget table including aggregated values
    * @param            string recordId 
    * @return           List<outfunds__Disbursement__c> 
    **/
    @AuraEnabled
    public static List<outfunds__Disbursement__c> getPayments(string recordId) {
        try {
            return [SELECT Id, outfunds__Scheduled_Date__c, Recommended__c, Plan__c, Awarded__c, Spend__c, Variance__c, Change__c, Payment_Amount__c FROM outfunds__Disbursement__c WHERE outfunds__Funding_Request__c=:recordId ORDER BY outfunds__Scheduled_Date__c ASC];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    /**
    * @description      method used for generating a new payment record and all associated budget lines
    * @param            string recordId 
    * @param            date paymentDate 
    * @return           string 
    **/
    @AuraEnabled
    public static string generatePayment(string recordId, date paymentDate) {
        try {
            
            outfunds__Disbursement__c payment = new outfunds__Disbursement__c(outfunds__Scheduled_Date__c = paymentDate,outfunds__Funding_Request__c = recordId);
            insert payment;

            List<Budget__c> budgets = [SELECT ID FROM Budget__c WHERE Funding_Request__c=:recordId];

            List<Budget_Line__c> insertBudgetLines = new List<Budget_Line__c>();

            for(Budget__c budget:budgets){
                Budget_Line__c budgetLine = new Budget_Line__c(Budget__c = budget.Id,Payment__c = payment.Id);
                insertBudgetLines.add(budgetLine);
            }

            database.insert(insertBudgetLines);
            return 'Success';
        
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description      method that will generate a new budget heading along with any associated budget lines should payments/disbursement existing in the system
    * @param            string recordId 
    * @param            string heading 
    * @return           string 
    **/
    @AuraEnabled
    public static string generateBudgetLine(string recordId, string heading){
        try {
            Budget__c budget = new Budget__c(Funding_Request__c = recordId, Heading__c = heading);
            insert budget;

            List<outfunds__Disbursement__c> disbursments = [SELECT Id FROM outfunds__Disbursement__c WHERE outfunds__Funding_Request__c=:recordId];

            List<Budget_Line__c> insertBudgetLines = new List<Budget_Line__c>();

            for(outfunds__Disbursement__c disbursment:disbursments){
                Budget_Line__c budgetLine = new Budget_Line__c(Payment__c = disbursment.Id, Budget__c = budget.Id);
                insertBudgetLines.add(budgetLine);
            }

            database.insert(insertBudgetLines);

            return 'Success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string saveChange(string recordId, string value, string fieldType){
        try {
            Budget_Line__c budgetLineUpdate = new Budget_Line__c(ID=recordId);
            switch on fieldType {
                when 'Plan'{
                    budgetLineUpdate.Plan__c = Decimal.valueOf(value);
                }
                when 'Recommended'{
                    budgetLineUpdate.Recommended__c = Decimal.valueOf(value);
                }
                when 'Spend'{
                    budgetLineUpdate.put('Spend__c', decimal.valueof(value));
                }
                when 'Change'{
                    budgetLineUpdate.put('Change__c', decimal.valueof(value));
                }
            }

            update budgetLineUpdate;

            return 'Success';
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}